pipeline {
    agent any
    environment{
    GRADLE_PROPERTIES = "gradle.properties"
    }
    options {
        // Keep last 5 build.
        buildDiscarder(logRotator(numToKeepStr: "5"))

        // Stop the build eagerly in case of compile or test failures.
        skipStagesAfterUnstable()
    }
    stage("Prepare gradle.properties") {
      steps {
        // Select Gradle properties.
        sh 'cp $GRADLE_PROPERTIES.sample $GRADLE_PROPERTIES'
      }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }

        stage('Compile'){
            steps {
            sh './gradlew compile'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }

    post{
         always{
             echo 'Just finished'
         }
    }
}
