pipeline {
    agent any

    options {
        // Keep last 5 build.
        buildDiscarder(logRotator(numToKeepStr: "5"))

        // Stop the build eagerly in case of compile or test failures.
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }

        stage('Compile'){
            steps {
            bat 'gradlew compile'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }

    post{
         always{
             echo 'Just finished'
         }
    }
}
