pipeline {
    agent any

    environment{
        BUILD_VARIANT = variant.fromBranch(BRANCH_NAME)
    }

    tools {
        // Ensures to build the project with JDK 11 as per Android Gradle
        // Plugin 7.0 requirements.
        //jdk "Open JDK 11"
    }

    options {
        // Keep last 5 build.
        buildDiscarder(logRotator(numToKeepStr: "5"))

        // Stop the build eagerly in case of compile or test failures.
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }

        stage('Compile'){
            steps {
            bat 'gradlew compile%{BUILD_VARIANT}'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }

    post{
         always{
             eho 'Just finished'
         }
    }
}
